{
  "id": "CVE-2023-41164",
  "description": "In Django 3.2 before 3.2.21, 4.1 before 4.1.11, and 4.2 before 4.2.5, django.utils.encoding.uri_to_iri() is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.",
  "debian_bug": 1051226,
  "scope": "local",
  "packages": [
    {
      "name": "python-django",
      "status": "resolved",
      "urgency": "not yet assigned",
      "fixed_version": "1:1.11.29-1+deb10u10",
      "repository": [
        {
          "name": "buster",
          "version": "1:1.11.29-1~deb10u1"
        },
        {
          "name": "buster-security",
          "version": "1:1.11.29-1+deb10u10"
        }
      ]
    }
  ]
}
