{
  "id": "CVE-2022-36087",
  "description": "OAuthLib is an implementation of the OAuth request-signing logic for Python 3.6+. In OAuthLib versions 3.1.1 until 3.2.1, an attacker providing malicious redirect uri can cause denial of service. An attacker can also leverage usage of `uri_validate` functions depending where it is used. OAuthLib applications using OAuth2.0 provider support or use directly `uri_validate` are affected by this issue. Version 3.2.1 contains a patch. There are no known workarounds.",
  "debian_bug": 1019710,
  "scope": "local",
  "packages": [
    {
      "name": "python-oauthlib",
      "status": "resolved",
      "urgency": "unimportant",
      "fixed_version": "0",
      "repository": [
        {
          "name": "buster",
          "version": "2.1.0-1"
        }
      ]
    }
  ]
}
