{
	"id": "CVE-2024-41990",
	"debian_bug": 1078074,
	"packages": [
		{
			"name": "python-django",
			"status": "open",
			"urgency": "not yet assigned",
			"repository": [
				{
					"name": "sid",
					"version": "3:4.2.14-1"
				}
			]
		}
	]
}
