{
	"id": "CVE-2023-40217",
	"description": "An issue was discovered in Python before 3.8.18, 3.9.x before 3.9.18, 3.10.x before 3.10.13, and 3.11.x before 3.11.5. It primarily affects servers (such as HTTP servers) that use TLS client authentication. If a TLS server-side socket is created, receives data into the socket buffer, and then is closed quickly, there is a brief window where the SSLSocket instance will detect the socket as \"not connected\" and won't initiate a handshake, but buffered data will still be readable from the socket buffer. This data will not be authenticated if the server-side TLS peer is expecting client certificate authentication, and is indistinguishable from valid TLS stream data. Data is limited in size to the amount that will fit in the buffer. (The TLS connection cannot directly be used for data exfiltration because the vulnerable code path requires that the connection be closed on initialization of the SSLSocket.)",
	"scope": "local",
	"packages": [
		{
			"name": "python3.10",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "3.10.13-1",
			"repository": [
				{
					"name": "sid",
					"version": "3.10.13-1"
				}
			]
		},
		{
			"name": "python3.11",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "3.11.5-1",
			"repository": [
				{
					"name": "sid",
					"version": "3.11.7-2"
				}
			]
		},
		{
			"name": "python3.12",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "3.12.0~rc1-2",
			"repository": [
				{
					"name": "sid",
					"version": "3.12.1-2"
				}
			]
		},
		{
			"name": "pypy3",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "7.3.13+dfsg-1",
			"repository": [
				{
					"name": "sid",
					"version": "7.3.14+dfsg-1"
				}
			]
		}
	]
}
