{
	"id": "CVE-2024-56374",
	"debian_bug": 1093049,
	"packages": [
		{
			"name": "python-django",
			"status": "open",
			"urgency": "not yet assigned",
			"repository": [
				{
					"name": "bullseye",
					"version": "2:2.2.28-1~deb11u2"
				},
				{
					"name": "bullseye-security",
					"version": "2:2.2.28-1~deb11u4"
				}
			]
		}
	]
}
