{
	"id": "CVE-2024-39614",
	"description": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. get_supported_language_variant() was subject to a potential denial-of-service attack when used with very long strings containing specific characters.",
	"debian_bug": 1076069,
	"scope": "local",
	"packages": [
		{
			"name": "python-django",
			"status": "open",
			"nodsa": "Minor issue",
			"nodsa_reason": "postponed",
			"urgency": "not yet assigned",
			"repository": [
				{
					"name": "bullseye",
					"version": "2:2.2.28-1~deb11u2"
				},
				{
					"name": "bullseye-security",
					"version": "2:2.2.28-1~deb11u4"
				}
			]
		}
	]
}
