{
	"id": "CVE-2024-38875",
	"description": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
	"debian_bug": 1076069,
	"scope": "local",
	"packages": [
		{
			"name": "python-django",
			"status": "open",
			"nodsa": "Minor issue; revisit after bookworm fix, if it is possible",
			"nodsa_reason": "postponed",
			"urgency": "not yet assigned",
			"repository": [
				{
					"name": "bullseye-security",
					"version": "2:2.2.28-1~deb11u4"
				},
				{
					"name": "bullseye",
					"version": "2:2.2.28-1~deb11u2"
				}
			]
		}
	]
}
